In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("loandataset.csv")
data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 52319 entries, 0 to 52318
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   LoanID          52319 non-null  str
 1   Age             52319 non-null  int64
 2   Income          52319 non-null  int64
 3   LoanAmount      52319 non-null  int64
 4   CreditScore     52319 non-null  int64
 5   MonthsEmployed  52319 non-null  int64
 6   NumCreditLines  52319 non-null  int64
 7   InterestRate    52319 non-null  float64
 8   LoanTerm        52319 non-null  int64
 9   DTIRatio        52319 non-null  float64
 10  Education       52319 non-null  str
 11  EmploymentType  52319 non-null  str
 12  MaritalStatus   52319 non-null  str
 13  HasMortgage     52319 non-null  str
 14  HasDependents   52319 non-null  str
 15  LoanPurpose     52319 non-null  str
 16  HasCoSigner     52319 non-null  str
 17  Default         52319 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 7.2 MB

In [4]:
data.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
data = pd.read_csv("loandataset.csv")
data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 52319 entries, 0 to 52318
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   LoanID          52319 non-null  str
 1   Age             52319 non-null  int64
 2   Income          52319 non-null  int64
 3   LoanAmount      52319 non-null  int64
 4   CreditScore     52319 non-null  int64
 5   MonthsEmployed  52319 non-null  int64
 6   NumCreditLines  52319 non-null  int64
 7   InterestRate    52319 non-null  float64
 8   LoanTerm        52319 non-null  int64
 9   DTIRatio        52319 non-null  float64
 10  Education       52319 non-null  str
 11  EmploymentType  52319 non-null  str
 12  MaritalStatus   52319 non-null  str
 13  HasMortgage     52319 non-null  str
 14  HasDependents   52319 non-null  str
 15  LoanPurpose     52319 non-null  str
 16  HasCoSigner     52319 non-null  str
 17  Default         52319 non-null  int64
dtypes: float64(2), int64(8), str(8)
memory usage: 7.2 MB

In [8]:
data.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [9]:
data.fillna(method='ffill', inplace=True)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [10]:
data = data.ffill()

In [11]:
data.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = le.fit_transform(data[column])

In [13]:
X = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

KeyError: "['Loan_Status'] not found in axis"

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'X' is not defined

In [15]:
X = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

KeyError: "['Loan_Status'] not found in axis"

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'X' is not defined

In [17]:
X = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

KeyError: "['Loan_Status'] not found in axis"

In [18]:
data.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='str')

In [19]:
X = data.drop('Default', axis=1)  # All columns except the target
y = data['Default']               # Target column

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
# Check categorical columns
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

# Convert categorical columns to numbers using one-hot encoding
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [22]:
from xgboost import XGBClassifier

# Create the model
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

# Train the model
model.fit(X_train, y_train)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, the experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:LoanID: str, Education: str, EmploymentType: str, MaritalStatus: str, HasMortgage: str, HasDependents: str, LoanPurpose: str, HasCoSigner: str

In [23]:
X = X.drop('LoanID', axis=1)

In [24]:
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

KeyError: "None of [Index(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',\n       'HasDependents', 'LoanPurpose', 'HasCoSigner'],\n      dtype='str')] are in the [columns]"

In [25]:
print(data.columns.tolist())

['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']

In [26]:
data.columns = data.columns.str.strip()

In [27]:
X = data.drop(['LoanID', 'Default'], axis=1)  # Drop ID & target
y = data['Default'].map({'No': 0, 'Yes': 1})  # Convert target to 0/1

In [28]:
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [29]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]

In [30]:
print(data['Default'].isnull().sum())

0

In [31]:
data = data.dropna(subset=['Default'])

In [32]:
# Only if you have a rule to fill
# data['Default'].fillna('No', inplace=True)

In [33]:
X = data.drop(['LoanID', 'Default'], axis=1)
y = data['Default'].map({'No': 0, 'Yes': 1})  # Convert to 0/1

In [34]:
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [35]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]

In [36]:
print(data['Default'].isnull().sum())

0

In [37]:
data = data.dropna(subset=['Default'])

In [38]:
y = data['Default'].map({'No': 0, 'Yes': 1})

In [39]:
X = data.drop(['LoanID', 'Default'], axis=1)
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [40]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]

In [41]:
print(data['Default'].unique())
print(data['Default'].isnull().sum())

[0 1]
0

In [42]:
data = data.dropna(subset=['Default'])

In [43]:
print(data['Default'].isnull().sum())  # Should print 0

0

In [44]:
y = data['Default'].map({'No': 0, 'Yes': 1})
print(y.unique())  # Should print [0, 1]

[nan]

In [45]:
X = data.drop(['LoanID', 'Default'], axis=1)

categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [47]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]

In [1]:
print(data['Default'].unique())
print(data['Default'].isnull().sum())

NameError: name 'data' is not defined

In [2]:
import pandas as pd

# Make sure the CSV file is in the same folder as your notebook
data = pd.read_csv("loandataset.csv")

# Check first 5 rows
data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [3]:
print(data['Default'].unique())
print(data['Default'].isnull().sum())

[0 1]
0

In [4]:
# Remove rows where 'Default' is NaN
data = data.dropna(subset=['Default'])

# If there are blank strings, remove them too
data = data[data['Default'].str.strip() != '']

# Convert target to numeric 0/1
y = data['Default'].map({'No': 0, 'Yes': 1})
print(y.unique())  # Should print [0, 1]

AttributeError: Can only use .str accessor with string values, not integer

In [5]:
import pandas as pd

# Load the dataset
data = pd.read_csv("loandataset.csv")

# Check target column
print(data['Default'].unique())
print(data['Default'].isnull().sum())

# Drop rows where Default is NaN (if any)
data = data.dropna(subset=['Default'])

# Make sure target is numeric (0/1)
# If it's already 0/1, this line is safe
y = data['Default'].astype(int)

# Select features (drop target column and LoanID)
X = data.drop(['Default', 'LoanID'], axis=1)

# Convert categorical columns to dummy/one-hot encoding
categorical_cols = ['Education', 'EmploymentType', 'MaritalStatus', 
                    'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

# Split into train/test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train XGBoost
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

[0 1]
0

c:\Users\kjine\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:32:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Model Accuracy: 0.8841743119266054

In [6]:
import pickle

# Save the model
with open("loan_model.pkl", "wb") as file:
    pickle.dump(model, file)